### ISSUE TITLE
計算、消去ボタンの高さが崩れる

### ISSUE THREAD

**Issue by hiko13** [tabinohito/Power-calculation-tool.io#1]
iPhone 12 Pro Max実機で確認。
iPhone8 Plus等の同様の縦長なデバイスで同現象が起きる。

![Image from iOS](https://user-images.githubusercontent.com/51507391/134812024-50b99841-1b80-4b6d-9ced-7139ef844bd5.png)

下記コードの箇所を検討するとよいかも。
```css
 .button{
    justify-content: space-between;
    align-items: center;
    margin: 0 auto;
    height: 40%; //高さの指定方法を再検討。なくてもよいかも。
    width: 100%;
    color: #333;
    font-size: 30px;
    font-weight: 700;
    background-color: #cccccc;
    /* transition: 0.3s; */
    }
```
